// <auto-generated />
using System;
using MicroserviceRgpd.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroserviceRgpd.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806092543_AddDeliveryGesturesAndLedgerCounts")]
    partial class AddDeliveryGesturesAndLedgerCounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdentityDeclaration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_declaration");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.DeclaredSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AdapterAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("adapter_address");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contents");

                    b.Property<DateTimeOffset>("DeclaredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_on");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<string[]>("_capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.HasKey("Id")
                        .HasName("pk_declared_systems");

                    b.ToTable("declared_systems", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.RetrievedData", b =>
                {
                    b.Property<Guid>("Case")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("Right")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_subject_right");

                    b.Property<string>("DeclaredSystem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("declared_system_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.HasKey("Case", "Right", "DeclaredSystem")
                        .HasName("pk_case_retrieved_data");

                    b.ToTable("case_retrieved_data", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Infrastructure.Data.Audit.QualificationAuditRow", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualification_id");

                    b.Property<string>("CallerReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("caller_reference");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReviewSignal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_signal");

                    b.PrimitiveCollection<string[]>("Rights")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rights");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("text");

                    b.Property<int>("TotalLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_latency_ms");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("VerdictDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("verdict_declared_confidence");

                    b.Property<string>("VerdictEngineName")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_name");

                    b.Property<string>("VerdictEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_version");

                    b.Property<int?>("VerdictLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("verdict_latency_ms");

                    b.PrimitiveCollection<string[]>("VerdictRights")
                        .HasColumnType("text[]")
                        .HasColumnName("verdict_rights");

                    b.Property<string>("WitnessDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("witness_declared_confidence");

                    b.Property<string>("WitnessEngineName")
                        .HasColumnType("text")
                        .HasColumnName("witness_engine_name");

                    b.Property<string>("WitnessEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("witness_engine_version");

                    b.Property<int?>("WitnessLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("witness_latency_ms");

                    b.PrimitiveCollection<string[]>("WitnessRights")
                        .HasColumnType("text[]")
                        .HasColumnName("witness_rights");

                    b.HasKey("QualificationId")
                        .HasName("pk_qualification_audit_entries");

                    b.ToTable("qualification_audit_entries", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Infrastructure.Data.Casework.EvidenceLogRow", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<int?>("CoveredSystemCount")
                        .HasColumnType("integer")
                        .HasColumnName("covered_system_count");

                    b.Property<string>("DataSubjectRight")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_subject_right");

                    b.Property<DateTimeOffset?>("DeclaredDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_deadline");

                    b.Property<string>("DeclaredSystem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("declared_system");

                    b.Property<int?>("DeclaredSystemCount")
                        .HasColumnType("integer")
                        .HasColumnName("declared_system_count");

                    b.Property<int?>("DesignationCount")
                        .HasColumnType("integer")
                        .HasColumnName("designation_count");

                    b.Property<string>("EvidenceProse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("evidence_prose");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fact");

                    b.Property<string>("IdentityDeclaration")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_declaration");

                    b.Property<string>("IdentityVerificationMethod")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_verification_method");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ReceivedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_on");

                    b.Property<bool?>("ReceptionWasDefaulted")
                        .HasColumnType("boolean")
                        .HasColumnName("reception_was_defaulted");

                    b.Property<string>("SignatoryKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signatory_kind");

                    b.Property<string>("SignatoryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("signatory_name");

                    b.Property<string>("SignerVerification")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signature_regime");

                    b.Property<string>("StepState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("step_state");

                    b.HasKey("EntryId")
                        .HasName("pk_ledger_entries");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.Case", b =>
                {
                    b.OwnsOne("MicroserviceRgpd.Core.Casework.IdentityMotivation", "Motivation", b1 =>
                        {
                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Detail")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("identity_motivation_detail");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("identity_verification_method");

                            b1.HasKey("CaseId");

                            b1.ToTable("cases");

                            b1.WithOwner()
                                .HasForeignKey("CaseId");
                        });

                    b.OwnsOne("MicroserviceRgpd.Core.Casework.ReceptionDate", "Reception", b1 =>
                        {
                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("reception_is_default");

                            b1.Property<DateTimeOffset>("On")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("received_on");

                            b1.HasKey("CaseId");

                            b1.ToTable("cases");

                            b1.WithOwner()
                                .HasForeignKey("CaseId");
                        });

                    b.OwnsMany("MicroserviceRgpd.Core.Casework.Designation", "Designations", b1 =>
                        {
                            b1.Property<Guid>("case_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("ordinal"));

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("kind");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("value");

                            b1.HasKey("case_id", "ordinal")
                                .HasName("pk_case_designations");

                            b1.ToTable("case_designations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("case_id")
                                .HasConstraintName("fk_case_designations_cases");
                        });

                    b.OwnsMany("MicroserviceRgpd.Core.Casework.Claim", "Claims", b1 =>
                        {
                            b1.Property<Guid>("case_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Right")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("data_subject_right");

                            b1.Property<bool>("Confirmed")
                                .HasColumnType("boolean")
                                .HasColumnName("confirmed");

                            b1.Property<DateTimeOffset?>("DeliveryDeclaredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_declared_on");

                            b1.Property<DateTimeOffset?>("DeliveryTakenOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_taken_on");

                            b1.Property<string>("IdentityAtOrigin")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("identity_at_origin");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("origin");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("state");

                            b1.HasKey("case_id", "Right")
                                .HasName("pk_case_claims");

                            b1.ToTable("case_claims", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("case_id")
                                .HasConstraintName("fk_case_claims_cases");

                            b1.OwnsMany("MicroserviceRgpd.Core.Casework.Step", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("case_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("data_subject_right")
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("DeclaredSystem")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("declared_system_id");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("state");

                                    b2.HasKey("case_id", "data_subject_right", "DeclaredSystem")
                                        .HasName("pk_case_steps");

                                    b2.ToTable("case_steps", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("case_id", "data_subject_right")
                                        .HasConstraintName("fk_case_steps_case_claims");
                                });

                            b1.Navigation("Steps");
                        });

                    b.OwnsMany("MicroserviceRgpd.Core.Casework.Locating", "Locatings", b1 =>
                        {
                            b1.Property<Guid>("case_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("DeclaredSystem")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("declared_system_id");

                            b1.Property<DateTimeOffset>("AskedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("asked_at");

                            b1.Property<DateTimeOffset?>("DeclaredDeadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("declared_deadline");

                            b1.Property<int>("DesignationsAtCall")
                                .HasColumnType("integer")
                                .HasColumnName("designations_at_call");

                            b1.Property<string>("LastOutcome")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("last_outcome");

                            b1.HasKey("case_id", "DeclaredSystem")
                                .HasName("pk_case_locatings");

                            b1.ToTable("case_locatings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("case_id")
                                .HasConstraintName("fk_case_locatings_cases");

                            b1.OwnsMany("MicroserviceRgpd.Core.Casework.OpaqueReference", "Certain", b2 =>
                                {
                                    b2.Property<Guid>("case_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("declared_system_id")
                                        .HasColumnType("character varying(64)");

                                    b2.Property<int>("ordinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("ordinal");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("ordinal"));

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("value");

                                    b2.HasKey("case_id", "declared_system_id", "ordinal")
                                        .HasName("pk_case_locating_references");

                                    b2.ToTable("case_locating_references", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("case_id", "declared_system_id")
                                        .HasConstraintName("fk_case_locating_references_case_locatings");
                                });

                            b1.OwnsMany("MicroserviceRgpd.Core.Casework.Reservation", "Reserved", b2 =>
                                {
                                    b2.Property<Guid>("case_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("declared_system_id")
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("Reference")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("reference");

                                    b2.Property<string>("Reason")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("reason");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("state");

                                    b2.HasKey("case_id", "declared_system_id", "Reference")
                                        .HasName("pk_case_reservations");

                                    b2.ToTable("case_reservations", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("case_id", "declared_system_id")
                                        .HasConstraintName("fk_case_reservations_case_locatings");

                                    b2.OwnsMany("MicroserviceRgpd.Core.Casework.Designation", "Designations", b3 =>
                                        {
                                            b3.Property<Guid>("case_id")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("declared_system_id")
                                                .HasColumnType("character varying(64)");

                                            b3.Property<string>("reference")
                                                .HasColumnType("character varying(200)");

                                            b3.Property<int>("ordinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer")
                                                .HasColumnName("ordinal");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("ordinal"));

                                            b3.Property<string>("Kind")
                                                .IsRequired()
                                                .HasMaxLength(64)
                                                .HasColumnType("character varying(64)")
                                                .HasColumnName("kind");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(400)
                                                .HasColumnType("character varying(400)")
                                                .HasColumnName("value");

                                            b3.HasKey("case_id", "declared_system_id", "reference", "ordinal")
                                                .HasName("pk_case_reservation_designations");

                                            b3.ToTable("case_reservation_designations", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("case_id", "declared_system_id", "reference")
                                                .HasConstraintName("fk_case_reservation_designations_case_reservations");
                                        });

                                    b2.Navigation("Designations");
                                });

                            b1.Navigation("Certain");

                            b1.Navigation("Reserved");
                        });

                    b.OwnsMany("MicroserviceRgpd.Core.Casework.OpenQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("case_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Subject")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("subject");

                            b1.Property<DateTimeOffset>("AskedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("asked_on");

                            b1.HasKey("case_id", "Subject")
                                .HasName("pk_case_questions");

                            b1.ToTable("case_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("case_id")
                                .HasConstraintName("fk_case_questions_cases");
                        });

                    b.OwnsMany("MicroserviceRgpd.Core.Casework.Reading", "Readings", b1 =>
                        {
                            b1.Property<Guid>("case_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Right")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("data_subject_right");

                            b1.Property<string>("DeclaredSystem")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("declared_system_id");

                            b1.Property<DateTimeOffset>("AskedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("asked_at");

                            b1.Property<DateTimeOffset?>("DeclaredDeadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("declared_deadline");

                            b1.Property<int>("DesignationsAtCall")
                                .HasColumnType("integer")
                                .HasColumnName("designations_at_call");

                            b1.Property<string>("LastOutcome")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("last_outcome");

                            b1.HasKey("case_id", "Right", "DeclaredSystem")
                                .HasName("pk_case_readings");

                            b1.ToTable("case_readings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("case_id")
                                .HasConstraintName("fk_case_readings_cases");
                        });

                    b.Navigation("Claims");

                    b.Navigation("Designations");

                    b.Navigation("Locatings");

                    b.Navigation("Motivation");

                    b.Navigation("Questions");

                    b.Navigation("Readings");

                    b.Navigation("Reception")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.RetrievedData", b =>
                {
                    b.OwnsOne("MicroserviceRgpd.Core.Casework.Adapters.TransportEnvelope", "Envelope", b1 =>
                        {
                            b1.Property<Guid>("RetrievedDataCase")
                                .HasColumnType("uuid");

                            b1.Property<string>("RetrievedDataRight")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("RetrievedDataDeclaredSystem")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.HasKey("RetrievedDataCase", "RetrievedDataRight", "RetrievedDataDeclaredSystem");

                            b1.ToTable("case_retrieved_data");

                            b1.WithOwner()
                                .HasForeignKey("RetrievedDataCase", "RetrievedDataRight", "RetrievedDataDeclaredSystem");
                        });

                    b.Navigation("Envelope")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
