// <auto-generated />
using System;
using MicroserviceRgpd.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroserviceRgpd.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803130521_CreateDeclaredSystems")]
    partial class CreateDeclaredSystems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceRgpd.Core.Casework.DeclaredSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AdapterAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("adapter_address");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contents");

                    b.Property<DateTimeOffset>("DeclaredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_on");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<string[]>("_capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.HasKey("Id")
                        .HasName("pk_declared_systems");

                    b.ToTable("declared_systems", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Infrastructure.Data.Audit.QualificationAuditRow", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualification_id");

                    b.Property<string>("CallerReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("caller_reference");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReviewSignal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_signal");

                    b.PrimitiveCollection<string[]>("Rights")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rights");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("text");

                    b.Property<int>("TotalLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_latency_ms");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("VerdictDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("verdict_declared_confidence");

                    b.Property<string>("VerdictEngineName")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_name");

                    b.Property<string>("VerdictEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_version");

                    b.Property<int?>("VerdictLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("verdict_latency_ms");

                    b.PrimitiveCollection<string[]>("VerdictRights")
                        .HasColumnType("text[]")
                        .HasColumnName("verdict_rights");

                    b.Property<string>("WitnessDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("witness_declared_confidence");

                    b.Property<string>("WitnessEngineName")
                        .HasColumnType("text")
                        .HasColumnName("witness_engine_name");

                    b.Property<string>("WitnessEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("witness_engine_version");

                    b.Property<int?>("WitnessLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("witness_latency_ms");

                    b.PrimitiveCollection<string[]>("WitnessRights")
                        .HasColumnType("text[]")
                        .HasColumnName("witness_rights");

                    b.HasKey("QualificationId")
                        .HasName("pk_qualification_audit_entries");

                    b.ToTable("qualification_audit_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
