// <auto-generated />
using System;
using MicroserviceRgpd.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroserviceRgpd.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911185225_AddDataSubjectRequestStatus")]
    partial class AddDataSubjectRequestStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceRgpd.Core.Configuration.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("access_url");

                    b.Property<string>("Erasure")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("erasure_url");

                    b.Property<string>("Objection")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("objection_url");

                    b.Property<string>("Portability")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("portability_url");

                    b.Property<string>("Rectification")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("rectification_url");

                    b.Property<string>("Restriction")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("restriction_url");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Requests.DataSubjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IdentityVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("identity_verified");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_subject_right");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_data_subject_requests");

                    b.ToTable("data_subject_requests", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Screenings.ScreenedColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("PreviewAbsence")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preview_absence_reason");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ScreeningId")
                        .HasColumnType("uuid")
                        .HasColumnName("screening_id");

                    b.Property<string>("Strength")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_screened_columns");

                    b.HasIndex("ScreeningId")
                        .HasDatabaseName("ix_screened_columns_screening_id");

                    b.ToTable("screened_columns", null, t =>
                        {
                            t.HasCheckConstraint("ck_screened_columns_arbitration", "(state is null and rendered_on is null) or (state is not null and rendered_on is not null)");
                        });
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Screenings.Screening", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_name");

                    b.Property<int>("DeclaredColumnCount")
                        .HasColumnType("integer")
                        .HasColumnName("declared_column_count");

                    b.Property<string>("Dialect")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dialect");

                    b.Property<DateTimeOffset>("LaunchedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launched_on");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("listing_origin");

                    b.HasKey("Id")
                        .HasName("pk_screenings");

                    b.ToTable("screenings", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Infrastructure.Data.Audit.QualificationAuditRow", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualification_id");

                    b.Property<string>("CallerReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("caller_reference");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("LexiconDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("lexicon_declared_confidence");

                    b.Property<string>("LexiconEngineName")
                        .HasColumnType("text")
                        .HasColumnName("lexicon_engine_name");

                    b.Property<string>("LexiconEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("lexicon_engine_version");

                    b.Property<int?>("LexiconLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("lexicon_latency_ms");

                    b.PrimitiveCollection<string[]>("LexiconRights")
                        .HasColumnType("text[]")
                        .HasColumnName("lexicon_rights");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReviewSignal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_signal");

                    b.PrimitiveCollection<string[]>("Rights")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rights");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("text");

                    b.Property<int>("TotalLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_latency_ms");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("VerdictDeclaredConfidence")
                        .HasColumnType("text")
                        .HasColumnName("verdict_declared_confidence");

                    b.Property<string>("VerdictEngineName")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_name");

                    b.Property<string>("VerdictEngineVersion")
                        .HasColumnType("text")
                        .HasColumnName("verdict_engine_version");

                    b.Property<int?>("VerdictLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("verdict_latency_ms");

                    b.PrimitiveCollection<string[]>("VerdictRights")
                        .HasColumnType("text[]")
                        .HasColumnName("verdict_rights");

                    b.HasKey("QualificationId")
                        .HasName("pk_qualification_audit_entries");

                    b.ToTable("qualification_audit_entries", (string)null);
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Screenings.ScreenedColumn", b =>
                {
                    b.HasOne("MicroserviceRgpd.Core.Screenings.Screening", null)
                        .WithMany("Columns")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screened_columns_screenings");

                    b.OwnsOne("MicroserviceRgpd.Core.Screenings.Arbitration", "Arbitration", b1 =>
                        {
                            b1.Property<Guid>("ScreenedColumnId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("RenderedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("rendered_on");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("state");

                            b1.HasKey("ScreenedColumnId");

                            b1.ToTable("screened_columns");

                            b1.WithOwner()
                                .HasForeignKey("ScreenedColumnId");
                        });

                    b.OwnsOne("MicroserviceRgpd.Core.Screenings.ListedColumn", "Listed", b1 =>
                        {
                            b1.Property<Guid>("ScreenedColumnId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ColumnComment")
                                .HasColumnType("text")
                                .HasColumnName("column_comment");

                            b1.Property<string>("DataType")
                                .HasColumnType("text")
                                .HasColumnName("data_type");

                            b1.Property<bool?>("IsNullable")
                                .HasColumnType("boolean")
                                .HasColumnName("is_nullable");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<string>("ReferencedTable")
                                .HasColumnType("text")
                                .HasColumnName("referenced_table");

                            b1.Property<string>("TableComment")
                                .HasColumnType("text")
                                .HasColumnName("table_comment");

                            b1.HasKey("ScreenedColumnId");

                            b1.ToTable("screened_columns");

                            b1.WithOwner()
                                .HasForeignKey("ScreenedColumnId");

                            b1.OwnsOne("MicroserviceRgpd.Core.Screenings.ColumnIdentity", "Identity", b2 =>
                                {
                                    b2.Property<Guid>("ListedColumnScreenedColumnId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Column")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("column_name");

                                    b2.Property<string>("Schema")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("schema_name");

                                    b2.Property<string>("Table")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("table_name");

                                    b2.HasKey("ListedColumnScreenedColumnId");

                                    b2.ToTable("screened_columns");

                                    b2.WithOwner()
                                        .HasForeignKey("ListedColumnScreenedColumnId");
                                });

                            b1.Navigation("Identity")
                                .IsRequired();
                        });

                    b.Navigation("Arbitration");

                    b.Navigation("Listed")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Screenings.Screening", b =>
                {
                    b.OwnsOne("MicroserviceRgpd.Core.Screenings.ScreeningEngineIdentity", "Engine", b1 =>
                        {
                            b1.Property<Guid>("ScreeningId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("engine_name");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("engine_version");

                            b1.HasKey("ScreeningId");

                            b1.ToTable("screenings");

                            b1.WithOwner()
                                .HasForeignKey("ScreeningId");
                        });

                    b.Navigation("Engine")
                        .IsRequired();
                });

            modelBuilder.Entity("MicroserviceRgpd.Core.Screenings.Screening", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
